services:
  - type: web
    name: cardiopredict
    env: python
    buildCommand: cd web_platform && pip install -r requirements.txt
    startCommand: cd web_platform && gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /
