services:
  - type: web
    name: cardiopredict
    env: python
    runtime: python
    buildCommand: cd web_platform && pip install --upgrade pip setuptools && pip install -r requirements-minimal.txt
    startCommand: cd web_platform && gunicorn --bind 0.0.0.0:$PORT app:app --timeout 120 --workers 1
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /
